//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatties.Model.UserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public Modulo()
        {
            this.NivelvsModulos = new HashSet<NivelvsModulo>();
        }
    
        public int ID { get; set; }
        public string nombre_Modulo { get; set; }
    
        public virtual ICollection<NivelvsModulo> NivelvsModulos { get; set; }
    }
}
