//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatties.Model.UserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Niveles_Acceso
    {
        public Niveles_Acceso()
        {
            this.Empleados = new HashSet<Empleado>();
            this.NivelvsModulos = new HashSet<NivelvsModulo>();
            this.Orden_de_Compra_Autorizaciones = new HashSet<Orden_de_Compra_Autorizaciones>();
        }
    
        public int ID { get; set; }
        public string NombreNivel { get; set; }
    
        public virtual ICollection<Empleado> Empleados { get; set; }
        public virtual ICollection<NivelvsModulo> NivelvsModulos { get; set; }
        public virtual ICollection<Orden_de_Compra_Autorizaciones> Orden_de_Compra_Autorizaciones { get; set; }
    }
}
