//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatties.Model.UserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_de_Compra_Autorizaciones
    {
        public int ID { get; set; }
        public int Empleado { get; set; }
        public int Nivel { get; set; }
        public Nullable<int> CC { get; set; }
        public Nullable<int> CC2 { get; set; }
        public Nullable<int> CC3 { get; set; }
        public Nullable<int> CC4 { get; set; }
    
        public virtual Empleado Empleado1 { get; set; }
        public virtual Niveles_Acceso Niveles_Acceso { get; set; }
    }
}
