//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatties.Model.UserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFILES_SUBMODULOS
    {
        public int idPerfil { get; set; }
        public int idSubmodulo { get; set; }
        public Nullable<bool> lee { get; set; }
        public Nullable<bool> actualiza { get; set; }
        public Nullable<bool> elimina { get; set; }
    
        public virtual PERFILES PERFILES { get; set; }
        public virtual SUBMODULOS SUBMODULOS { get; set; }
    }
}
