//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatties.Model.UserManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBMODULOS
    {
        public SUBMODULOS()
        {
            this.PERFILES_SUBMODULOS = new HashSet<PERFILES_SUBMODULOS>();
        }
    
        public int idModulo { get; set; }
        public int idSubmodulo { get; set; }
        public string descSubmodulo { get; set; }
        public string url { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual MODULOS1 MODULOS1 { get; set; }
        public virtual ICollection<PERFILES_SUBMODULOS> PERFILES_SUBMODULOS { get; set; }
    }
}
