//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatties.Model.UserManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ENLASYSEntities : DbContext
    {
        public ENLASYSEntities()
            : base("name=ENLASYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Empleado> Empleados { get; set; }
        public DbSet<Modulo> Modulos { get; set; }
        public DbSet<Niveles_Acceso> Niveles_Acceso { get; set; }
        public DbSet<NivelvsModulo> NivelvsModulos { get; set; }
        public DbSet<Orden_de_Compra_Autorizaciones> Orden_de_Compra_Autorizaciones { get; set; }
        public DbSet<MODULOS1> MODULOS1 { get; set; }
        public DbSet<PERFILES_SUBMODULOS> PERFILES_SUBMODULOS { get; set; }
        public DbSet<SUBMODULOS> SUBMODULOS { get; set; }
        public DbSet<PERFILES> PERFILES { get; set; }
    
        public virtual int InsertaUsuario(string nombre, string apPaterno, string apMaterno, string usuario, string pwd, string correo, Nullable<int> idNivelAcceso)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apPaternoParameter = apPaterno != null ?
                new ObjectParameter("apPaterno", apPaterno) :
                new ObjectParameter("apPaterno", typeof(string));
    
            var apMaternoParameter = apMaterno != null ?
                new ObjectParameter("apMaterno", apMaterno) :
                new ObjectParameter("apMaterno", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var idNivelAccesoParameter = idNivelAcceso.HasValue ?
                new ObjectParameter("idNivelAcceso", idNivelAcceso) :
                new ObjectParameter("idNivelAcceso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertaUsuario", nombreParameter, apPaternoParameter, apMaternoParameter, usuarioParameter, pwdParameter, correoParameter, idNivelAccesoParameter);
        }
    
        public virtual int ActualizaUsuario(Nullable<int> idUsuario, string nombre, string apPaterno, string apMaterno, string usuario, string pwd, string correo, Nullable<int> idNivelAcceso)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apPaternoParameter = apPaterno != null ?
                new ObjectParameter("apPaterno", apPaterno) :
                new ObjectParameter("apPaterno", typeof(string));
    
            var apMaternoParameter = apMaterno != null ?
                new ObjectParameter("apMaterno", apMaterno) :
                new ObjectParameter("apMaterno", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var idNivelAccesoParameter = idNivelAcceso.HasValue ?
                new ObjectParameter("idNivelAcceso", idNivelAcceso) :
                new ObjectParameter("idNivelAcceso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizaUsuario", idUsuarioParameter, nombreParameter, apPaternoParameter, apMaternoParameter, usuarioParameter, pwdParameter, correoParameter, idNivelAccesoParameter);
        }
    
        public virtual int BorraUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorraUsuario", idUsuarioParameter);
        }
    
        public virtual ObjectResult<ObtenMenu_Result> ObtenMenu(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenMenu_Result>("ObtenMenu", idUsuarioParameter);
        }
    }
}
