//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChattiesModel.User_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Orden_de_Compra_Autorizaciones = new HashSet<Orden_de_Compra_Autorizaciones>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string contrasena { get; set; }
        public string usuario { get; set; }
        public Nullable<int> NivelAcceso { get; set; }
        public string encPassword { get; set; }
        public string apPaterno { get; set; }
        public string apMaterno { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Niveles_Acceso Niveles_Acceso { get; set; }
        public virtual ICollection<Orden_de_Compra_Autorizaciones> Orden_de_Compra_Autorizaciones { get; set; }
    }
}
