//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChattiesModel.User_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public Modulo()
        {
            this.NivelvsModulos = new HashSet<NivelvsModulo>();
        }
    
        public int ID { get; set; }
        public string nombre_Modulo { get; set; }
    
        public virtual ICollection<NivelvsModulo> NivelvsModulos { get; set; }
    }
}
