//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChattiesModel.User_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class NivelvsModulo
    {
        public int id { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> modulo { get; set; }
        public Nullable<bool> Agrega { get; set; }
        public Nullable<bool> Modifica { get; set; }
        public Nullable<bool> Elimina { get; set; }
        public Nullable<bool> Autoriza { get; set; }
    
        public virtual Modulo Modulo1 { get; set; }
        public virtual Niveles_Acceso Niveles_Acceso { get; set; }
    }
}
