//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChattiesModel.User_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Niveles_Acceso
    {
        public Niveles_Acceso()
        {
            this.Empleados = new HashSet<Empleado>();
            this.NivelvsModulos = new HashSet<NivelvsModulo>();
            this.Orden_de_Compra_Autorizaciones = new HashSet<Orden_de_Compra_Autorizaciones>();
        }
    
        public int ID { get; set; }
        public string NombreNivel { get; set; }
    
        public virtual ICollection<Empleado> Empleados { get; set; }
        public virtual ICollection<NivelvsModulo> NivelvsModulos { get; set; }
        public virtual ICollection<Orden_de_Compra_Autorizaciones> Orden_de_Compra_Autorizaciones { get; set; }
    }
}
