//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChattiesModel.User_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class NivelvsModulo
    {
        public int id { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> modulo { get; set; }
        public Nullable<bool> Agrega { get; set; }
        public Nullable<bool> Modifica { get; set; }
        public Nullable<bool> Elimina { get; set; }
        public Nullable<bool> Autoriza { get; set; }
    
        public virtual Modulo Modulo1 { get; set; }
        public virtual Niveles_Acceso Niveles_Acceso { get; set; }
    }
}
