//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChattiesModel.User_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_de_Compra_Autorizaciones
    {
        public int ID { get; set; }
        public int Empleado { get; set; }
        public int Nivel { get; set; }
        public Nullable<int> CC { get; set; }
        public Nullable<int> CC2 { get; set; }
        public Nullable<int> CC3 { get; set; }
        public Nullable<int> CC4 { get; set; }
    
        public virtual Empleado Empleado1 { get; set; }
        public virtual Niveles_Acceso Niveles_Acceso { get; set; }
    }
}
