//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChattiesModel.User_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFILES
    {
        public PERFILES()
        {
            this.PERFILES_SUBMODULOS = new HashSet<PERFILES_SUBMODULOS>();
            this.Empleados = new HashSet<Empleado>();
        }
    
        public int idPerfil { get; set; }
        public string descPerfil { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual ICollection<PERFILES_SUBMODULOS> PERFILES_SUBMODULOS { get; set; }
        public virtual ICollection<Empleado> Empleados { get; set; }
    }
}
