//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChattiesModel.User_Management
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ENLASYSEntities : DbContext
    {
        public ENLASYSEntities()
            : base("name=ENLASYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Empleado> Empleados { get; set; }
        public DbSet<Modulo> Modulos { get; set; }
        public DbSet<Niveles_Acceso> Niveles_Acceso { get; set; }
        public DbSet<NivelvsModulo> NivelvsModulos { get; set; }
        public DbSet<Orden_de_Compra_Autorizaciones> Orden_de_Compra_Autorizaciones { get; set; }
    }
}
